# Generated by Django 5.0.6 on 2024-07-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('contrasena', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_ultima_conexion', models.DateTimeField()),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
