# Generated by Django 5.0.6 on 2024-07-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_opcion', models.CharField(default='nombre_opcion', max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Opciones',
            },
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_modificacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
        migrations.CreateModel(
            name='Opciones_Usuarios',
            fields=[
                ('id_opcion_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField()),
                ('usuario_asignacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('Opciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.opciones')),
                ('Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
            ],
            options={
                'db_table': 'Opciones_Usuarios',
            },
        ),
    ]
