# Generated by Django 5.0.6 on 2024-07-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_opciones_alter_usuarios_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
