# Generated by Django 5.0.6 on 2024-07-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
