# Generated by Django 5.0.6 on 2024-07-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_usuarios_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opciones_usuarios',
            old_name='fecha_asignacion',
            new_name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='nombre_opcion',
        ),
        migrations.RemoveField(
            model_name='opciones_usuarios',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='opciones_usuarios',
            name='usuario_asignacion',
        ),
        migrations.AddField(
            model_name='opciones',
            name='eliminar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=50),
        ),
        migrations.AddField(
            model_name='opciones',
            name='ingresar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='modificar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='solo_lectura',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones_usuarios',
            name='usuario_modificacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
