# Generated by Django 5.0.6 on 2024-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_rename_fecha_asignacion_opciones_usuarios_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='eliminar',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='estado',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='ingresar',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='modificar',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='solo_lectura',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100),
        ),
    ]
