# Generated by Django 5.0.6 on 2024-07-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_alter_opciones_eliminar_alter_opciones_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='eliminar',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='ingresar',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='modificar',
        ),
        migrations.AlterField(
            model_name='opciones',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='solo_lectura',
            field=models.CharField(max_length=100),
        ),
    ]
