# Generated by Django 5.0.6 on 2024-07-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_rename_estado_opciones_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Promociones_Clientes',
            fields=[
                ('id_promocion_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('monto_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=1)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes')),
                ('id_promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.promociones')),
            ],
            options={
                'db_table': 'Promociones_Clientes',
            },
        ),
        migrations.CreateModel(
            name='Promociones_Productos',
            fields=[
                ('id_promocion_producto', models.AutoField(primary_key=True, serialize=False)),
                ('monto_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=1)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.productos')),
                ('id_promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.promociones')),
            ],
            options={
                'db_table': 'Promociones_Productos',
            },
        ),
        migrations.CreateModel(
            name='Visita_Tienda_Clientes',
            fields=[
                ('id_Tienda_Visita_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateTimeField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tiendas')),
            ],
            options={
                'db_table': 'Visita_Tienda_Clientes',
            },
        ),
    ]
