# Generated by Django 5.0.6 on 2024-07-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_clientes_productos_promociones_tiendas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_visita', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes')),
            ],
            options={
                'db_table': 'HistorialVisita',
            },
        ),
    ]
